[package]
name = "IpTellDnspod"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.8"
hmac = "0.12"
sha2 = "0.10"
sqlx = { version = "0.8",features = [ "sqlite", "runtime-tokio", "tls-native-tls" ] }
